#!/usr/bin/env python

import os
import shutil
from diffusers import StableDiffusionPipeline, DiffusionPipeline

from shutil import copyfile
from huggingface_hub import snapshot_download

MODEL_CACHE = "diffusers-cache"


model_list = ["runwayml/stable-diffusion-v1-5"]

for model in model_list:
    if os.path.exists(MODEL_CACHE):
        shutil.rmtree(MODEL_CACHE)
    os.makedirs(MODEL_CACHE, exist_ok=True)
   
    pipe = DiffusionPipeline.from_pretrained(
        pretrained_model_name_or_path=model,
        safety_checker=None,
        custom_pipeline="lpw_stable_diffusion",
    )
    pipe.save_pretrained("./"+MODEL_CACHE+"/"+model)

#   I also made a thing that downloads lora files from huggingface to the /lora folder, but I figured you wouldn't need it here
